import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const productsSrc = readFileSync(join(root, 'lib/products.ts'), 'utf8')
const siteSrc = readFileSync(join(root, 'lib/site.ts'), 'utf8')
const netlify = readFileSync(join(root, 'netlify.toml'), 'utf8')

describe('product portfolio', () => {
  it('exposes named products with distinct domains', () => {
    for (const slug of ['mint', 'repave', 'overpass', 'toll', 'dispatch']) {
      assert.match(productsSrc, new RegExp(`slug: '${slug}'`))
    }
    assert.match(productsSrc, /Governed automation language/)
    assert.match(productsSrc, /Governed software delivery/)
    assert.match(productsSrc, /Infrastructure state and understanding/)
    assert.match(productsSrc, /Engineering economics/)
    assert.match(productsSrc, /Governed intelligent experience/)
  })

  it('does not treat Repave as the umbrella or Dispatch as a data domain', () => {
    assert.match(productsSrc, /not the OpsDevCode umbrella/)
    assert.match(productsSrc, /not a fourth data domain/)
    assert.match(productsSrc, /maturity: 'public-preview'/)
    assert.match(productsSrc, /maturity: 'early-access'/)
    assert.match(productsSrc, /maturity: 'in-development'/)
    assert.match(productsSrc, /maturity: 'emerging'/)
    assert.match(productsSrc, /compareRole: 'Govern delivery'/)
    assert.match(productsSrc, /compareRole: 'Ask and act'/)
  })

  it('gives every product the same editorial density as Repave', () => {
    const ownsBlocks = [...productsSrc.matchAll(/owns: \[([\s\S]*?)\],/g)]
    assert.equal(ownsBlocks.length, 5)
    for (const block of ownsBlocks) {
      const items = [...block[1].matchAll(/'/g)].length / 2
      assert.ok(items >= 6, `owns list too thin: ${block[1]}`)
    }
    assert.match(productsSrc, /Name\. Compile\. Realize\. Plan\./)
    assert.match(productsSrc, /Custody\. Relationships\. Drift\. Impact\. Transactions\./)
    assert.match(productsSrc, /Spend\. Ownership\. Utilization\. Evidence\./)
    assert.match(productsSrc, /Intent\. Proposal\. Gate\. Action\./)
    assert.match(productsSrc, /Generate\. Adopt\. Configure\. Upgrade\. Observe\. Remediate\./)
  })

  it('routes visitor site links to live hosts or company product pages', () => {
    assert.match(siteSrc, /repave: 'https:\/\/repave\.opsdevco\.de'/)
    assert.match(siteSrc, /overpass: 'https:\/\/overpass\.opsdevco\.de'/)
    assert.match(siteSrc, /toll: 'https:\/\/toll\.opsdevco\.de'/)
    assert.match(siteSrc, /dispatch: 'https:\/\/dispatch\.opsdevco\.de'/)
    assert.match(siteSrc, /overpass: true/)
    assert.match(siteSrc, /toll: true/)
    assert.match(siteSrc, /dispatch: true/)
    assert.doesNotMatch(siteSrc, /overpass: false/)
    assert.doesNotMatch(siteSrc, /toll: false/)
    assert.doesNotMatch(siteSrc, /dispatch: false/)
    assert.match(productsSrc, /publicUrl: '\/products\/mint'/)
    assert.match(productsSrc, /publicUrl: productSiteHref\('repave'\)/)
    assert.match(productsSrc, /publicUrl: productSiteHref\('overpass'\)/)
    assert.match(productsSrc, /publicUrl: productSiteHref\('toll'\)/)
    assert.match(productsSrc, /publicUrl: productSiteHref\('dispatch'\)/)
    assert.doesNotMatch(productsSrc, /github.com\/opsdevcode\/overpass/)
    assert.doesNotMatch(productsSrc, /github.com\/opsdevcode\/toll/)
    assert.doesNotMatch(productsSrc, /github.com\/opsdevcode\/dispatch/)
    assert.doesNotMatch(productsSrc, /github.com\/opsdevcode\/repave/)
    assert.match(productsSrc, /See the governed lifecycle/)
    assert.match(siteSrc, /REPAVE_PROOF_URL = `\$\{REPAVE_URL\}\/proof`/)
    assert.match(siteSrc, /REPAVE_EVALUATE_URL = `\$\{REPAVE_WAITLIST_URL\}\?intent=evaluate`/)
    assert.doesNotMatch(siteSrc, /mint: 'https:\/\/mint\.opsdevco\.de'/)
    assert.doesNotMatch(productsSrc, /mint\.opsdevco/)
    assert.match(productsSrc, /ctaHref: MINT_QUICKSTART_URL/)
    assert.match(productsSrc, /ctaHref: REPAVE_EVALUATE_URL/)
    assert.match(productsSrc, /ctaHref: PRODUCT_URLS\.overpass/)
    assert.match(productsSrc, /ctaHref: PRODUCT_URLS\.toll/)
    assert.match(productsSrc, /ctaHref: PRODUCT_URLS\.dispatch/)
    assert.doesNotMatch(productsSrc, /waitlistUrl\('overpass'\)/)
    assert.doesNotMatch(productsSrc, /\/try/)
    assert.doesNotMatch(siteSrc, /\/try/)
  })

  it('does not rewrite product identity hosts onto the company Netlify site', () => {
    assert.doesNotMatch(netlify, /https:\/\/overpass\.opsdevco\.de\/\*/)
    assert.doesNotMatch(netlify, /https:\/\/toll\.opsdevco\.de\/\*/)
    assert.doesNotMatch(netlify, /https:\/\/dispatch\.opsdevco\.de\/\*/)
  })

  it('does not treat Convergence as a product host', () => {
    assert.doesNotMatch(siteSrc, /convergence\.opsdevco/)
    assert.doesNotMatch(netlify, /convergence\.opsdevco/)
  })

  it('builds robots sitemap from SITE_URL', () => {
    const robots = readFileSync(join(root, 'src/app/robots.ts'), 'utf8')
    assert.match(robots, /sitemap: `\$\{SITE_URL\}\/sitemap\.xml`/)
  })

  it('keeps the company thesis architectural', () => {
    assert.match(siteSrc, /Infrastructure for modern engineering organizations/)
    assert.match(siteSrc, /OpsDevCode is the company/)
    assert.match(siteSrc, /OpsDevCode Platform is the modular offering/)
    assert.doesNotMatch(siteSrc, /Governed golden paths for platform engineering/)
    assert.doesNotMatch(siteSrc, /intelligent platform layer/)
    assert.doesNotMatch(siteSrc, /Platform engineering as a service/)
  })

  it('uses the governed-section mark on company chrome, not raster banners', () => {
    const header = readFileSync(join(root, 'components/Header.tsx'), 'utf8')
    const footer = readFileSync(join(root, 'components/Footer.tsx'), 'utf8')
    const layout = readFileSync(join(root, 'src/app/layout.tsx'), 'utf8')
    const seo = readFileSync(join(root, 'lib/seo.ts'), 'utf8')
    assert.match(siteSrc, /COMPANY_MARK_SRC = '\/brand\/mark-opsdevcode\.svg'/)
    assert.match(siteSrc, /COMPANY_LOCKUP_SRC = '\/brand\/lockup-opsdevcode\.svg'/)
    assert.match(siteSrc, /COMPANY_LOGO_SRC = '\/brand\/favicon-opsdevcode\.svg'/)
    assert.match(header, /BrandMark/)
    assert.match(footer, /ProductMark/)
    assert.match(footer, /product\.name/)
    assert.match(footer, /BrandMark/)
    assert.match(layout, /COMPANY_LOGO_SRC/)
    assert.match(layout, /IBM_Plex_Sans/)
    assert.match(siteSrc, /SITE_SHARE_TITLE/)
    assert.match(seo, /SITE_SHARE_TITLE/)
    assert.doesNotMatch(header, /opsdevco-banner/)
    assert.doesNotMatch(footer, /opsdevco-banner/)
    assert.doesNotMatch(header, /opsdevco-logo-o-terminal/)
    assert.doesNotMatch(footer, /opsdevco-logo-o-terminal/)
    assert.doesNotMatch(layout, /opsdevco-logo-o-terminal/)
    assert.equal(existsSync(join(root, 'logo-preview.html')), false)
    for (const retired of [
      'public/assets/opsdevco-logo.png',
      'public/assets/opsdevco-logo-o-mark.png',
      'public/assets/opsdevco-logo-o-terminal.png',
      'public/assets/opsdevco-banner.png',
    ]) {
      assert.equal(existsSync(join(root, retired)), false, retired)
    }
    assert.equal(existsSync(join(root, 'public/brand/github-avatar-opsdevcode.png')), true)
  })

  it('uses a parent-brand homepage, not a fifth product sales page', () => {
    const home = readFileSync(join(root, 'src/app/page.tsx'), 'utf8')
    const header = readFileSync(join(root, 'components/Header.tsx'), 'utf8')
    assert.match(home, /OUTCOME_LINE/)
    assert.match(home, /GOVERN_LINE/)
    assert.match(home, /VERIFY_LINE/)
    const platform = readFileSync(join(root, 'lib/platform.ts'), 'utf8')
    assert.match(platform, /Define the outcome/)
    assert.match(platform, /Govern the change/)
    assert.match(platform, /Verify the result/)
    assert.match(home, /See the products/)
    assert.match(home, /Talk to OpsDevCode/)
    assert.match(home, /Mint, then four domain products/)
    assert.match(home, /Independently adoptable/)
    assert.match(home, /Different engineering problems/)
    assert.match(home, /Start with the problem/)
    assert.match(home, /Built as a product company/)
    assert.match(home, /PLATFORM_NAME/)
    assert.match(home, /home-product-names/)
    assert.match(home, /name: 'Mint'/)
    assert.match(home, /\$\{SITE_URL\}\/products\/mint/)
    assert.match(home, /Mint/)
    assert.match(home, /Repave/)
    assert.match(home, /Overpass/)
    assert.match(home, /Toll/)
    assert.match(home, /Dispatch/)
    assert.match(home, /PRODUCT_URLS/)
    assert.match(home, /href="\/architecture"/)
    assert.match(home, /variant="portfolio"/)
    assert.doesNotMatch(home, /THESIS/)
    assert.doesNotMatch(home, /PARENT SYSTEM/)
    assert.doesNotMatch(home, /Start free/)
    assert.doesNotMatch(home, /Try it now/)
    assert.doesNotMatch(home, /Deploy the platform/)
    assert.doesNotMatch(home, /Connect your cloud/)
    assert.doesNotMatch(home, /See all four working together/)
    assert.doesNotMatch(home, /Explore the system/)
    assert.doesNotMatch(home, /SystemMap/)
    assert.doesNotMatch(home, /problem-planes/)
    assert.doesNotMatch(home, /variant="hero"/)
    assert.doesNotMatch(home, /variant="family"/)
    assert.doesNotMatch(home, /product-lines/)
    assert.doesNotMatch(home, /Start Free/)
    assert.doesNotMatch(home, /\/try/)
    assert.doesNotMatch(home, /ConvergePair/)
    assert.doesNotMatch(home, /intelligent platform layer/)
    assert.doesNotMatch(home, /Policy Runtime/)
    assert.doesNotMatch(home, /Open Policy Agent/)
    assert.doesNotMatch(home, /\bRelay\b/)
    assert.match(header, /label: 'Products'/)
    assert.match(header, /label: 'Approach'/)
    assert.match(header, /label: 'Architecture'/)
    assert.match(header, /label: 'Company'/)
    assert.match(header, /label: 'Talk'/)
    assert.doesNotMatch(header, /Convergence/)
    assert.doesNotMatch(header, /Services/)
    assert.doesNotMatch(header, /GitHub/)
  })

  it('adds a company architecture page that is not a fifth product', () => {
    const architecture = readFileSync(join(root, 'src/app/architecture/page.tsx'), 'utf8')
    const header = readFileSync(join(root, 'components/Header.tsx'), 'utf8')
    const sitemap = readFileSync(join(root, 'src/app/sitemap.ts'), 'utf8')
    assert.match(architecture, /modular platform/)
    assert.match(architecture, /not a fifth product/)
    assert.match(architecture, /SpecMint/)
    assert.match(architecture, /Relay/)
    assert.match(architecture, /object-storage/)
    assert.match(architecture, /Repave is\s+optional/)
    assert.match(architecture, /Open Policy Agent/)
    assert.match(header, /\/architecture/)
    assert.match(sitemap, /\/architecture/)
    assert.doesNotMatch(architecture, /fully automated compliance/)
    assert.doesNotMatch(architecture, /production-proven policy control plane/)
  })

  it('publishes Mint as the public entry product on a dedicated page', () => {
    const mintPage = readFileSync(join(root, 'src/app/products/mint/page.tsx'), 'utf8')
    const about = readFileSync(join(root, 'src/app/about/page.tsx'), 'utf8')
    const approach = readFileSync(join(root, 'src/app/approach/page.tsx'), 'utf8')
    const architecture = readFileSync(join(root, 'src/app/architecture/page.tsx'), 'utf8')
    assert.equal(existsSync(join(root, 'src/app/products/mint/page.tsx')), true)
    assert.equal(existsSync(join(root, 'public/brand/mark-mint.svg')), true)
    assert.match(mintPage, /pipx install specmint/)
    assert.match(mintPage, /uv tool install specmint/)
    assert.match(mintPage, /Get started/)
    assert.match(mintPage, /View source/)
    assert.match(mintPage, /Build an integration/)
    assert.match(mintPage, /What Mint does/)
    assert.match(mintPage, /Mint versus SpecMint/)
    assert.match(mintPage, /How it fits/)
    assert.match(mintPage, /Working quickstart/)
    assert.match(mintPage, /Integration ecosystem/)
    assert.match(mintPage, /Community/)
    assert.match(mintPage, /mint\.catalog-records\/v0/)
    assert.match(mintPage, /does not pip-install/)
    assert.match(mintPage, /repo\.github/)
    assert.match(mintPage, /GitHub SDK/)
    assert.match(mintPage, /mint-integration-local/)
    assert.match(mintPage, /mint-integration-github/)
    assert.match(mintPage, /GitHub Releases, not PyPI/)
    assert.doesNotMatch(mintPage, /pypi.org\/project\/mint-integration/)
    assert.match(mintPage, /one-shot process supervisor/)
    assert.match(mintPage, /does not import Repave/)
    assert.match(mintPage, /no Kubernetes snapshot integration/)
    assert.match(mintPage, /examples\/projects\/local-marker/)
    assert.match(mintPage, /local\.sandbox/)
    assert.match(mintPage, /Safety/)
    assert.match(mintPage, /MINT_QUICKSTART_URL/)
    assert.match(mintPage, /MINT_LANGUAGE_URL/)
    assert.match(mintPage, /MINT_INTEGRATION_PROTOCOL_URL/)
    assert.match(mintPage, /MINT_INTEGRATION_AUTHORING_URL/)
    assert.match(mintPage, /SPECMINT_PLATFORM_URL/)
    assert.match(mintPage, /MINT_ISSUES_URL/)
    assert.match(mintPage, /not production-ready/)
    assert.match(mintPage, /<blockquote className="product-quote">/)
    assert.match(
      mintPage,
      /Mint is the public entry product: the language, CLI, SDK, editor, and protocol/
    )
    assert.match(mintPage, /governed lifecycle runtime behind Mint/)
    assert.match(mintPage, /not a customer SKU/)
    assert.match(mintPage, /ten-minute loop/)
    assert.match(mintPage, /mint integrations test/)
    assert.match(mintPage, /approval, fake\/local execution, verification, and evidence/)
    assert.match(mintPage, /no Marketplace listing/)
    assert.match(mintPage, /No default live provider execution/)
    assert.doesNotMatch(mintPage, /\b1\.0\b/)
    assert.doesNotMatch(mintPage, /Open VSX/)
    assert.match(siteSrc, /MINT_DOCS_URL = 'https:\/\/opsdevcode\.github\.io\/specmint-language\/'/)
    assert.match(siteSrc, /MINT_QUICKSTART_URL = `\$\{MINT_DOCS_URL\}docs\/quickstart\.html`/)
    assert.doesNotMatch(siteSrc, /blob\/main\/docs\/quickstart/)
    assert.doesNotMatch(mintPage, /specmint==/)
    assert.doesNotMatch(mintPage, /0\.1\.0a2/)
    assert.doesNotMatch(mintPage, /href=["']#/)
    assert.doesNotMatch(approach, /not a published syntax/)
    assert.match(about, /Yes\. Mint is the public entry product/)
    assert.match(architecture, /Mint is the public entry/)
    assert.match(productsSrc, /maturityIndex: '00'/)
    assert.match(productsSrc, /Not production-ready/)
  })

  it('does not overclaim Overpass live-cloud, Toll savings, or Dispatch autonomy', () => {
    const home = readFileSync(join(root, 'src/app/page.tsx'), 'utf8')
    const productsPage = readFileSync(join(root, 'src/app/products/page.tsx'), 'utf8')
    assert.doesNotMatch(productsSrc, /blast radius from a proposed or live change/i)
    assert.doesNotMatch(productsSrc, /Commitment coverage as evidence/)
    assert.doesNotMatch(productsSrc, /Waste findings as evidence/)
    assert.match(productsSrc, /No savings percentages/)
    assert.match(productsSrc, /not live-cloud/)
    assert.match(productsSrc, /still execute in Repave/)
    assert.match(productsSrc, /spend\/waste execution still in Repave/)
    assert.match(productsSrc, /does not approve its own work/)
    assert.doesNotMatch(productsSrc, /A single interaction surface across the four jobs/)
    assert.doesNotMatch(productsSrc, /realized savings/)
    assert.doesNotMatch(home, /attributes the spend/)
    assert.doesNotMatch(home, /reads the estate/)
    assert.match(productsPage, /not yet a\s+standalone four-product interaction surface/)
    assert.match(productsPage, /Problem/)
    assert.match(productsPage, /Input/)
    assert.match(productsPage, /Outcome/)
    assert.match(productsPage, /Availability/)
    assert.match(productsPage, /Next step/)
    assert.match(productsPage, /Team/)
    assert.match(productsPage, /Growth/)
    assert.doesNotMatch(productsPage, /\$\d/)
    assert.match(productsSrc, /compareProblem/)
    assert.match(productsSrc, /nextStepLabel: 'Request early access'/)
  })

  it('keeps Convergence off the product hierarchy on the homepage', () => {
    const home = readFileSync(join(root, 'src/app/page.tsx'), 'utf8')
    const footer = readFileSync(join(root, 'components/Footer.tsx'), 'utf8')
    assert.match(home, /independent research/)
    assert.match(home, /not an OpsDevCode\s+product/)
    assert.doesNotMatch(home, /slug: 'convergence'/)
    assert.match(footer, /CONVERGENCE_URL/)
  })
})

describe('services and a11y basics', () => {
  it('keeps indexed service slugs and company voice', () => {
    const services = readFileSync(join(root, 'lib/services-detail.ts'), 'utf8')
    for (const slug of [
      'platform-health',
      'finops',
      'iac',
      'cicd',
      'kubernetes',
      'custom-tooling',
      'architecture-review',
      'fractional-advisor',
    ]) {
      assert.match(services, new RegExp(`slug: '${slug}'`))
    }
    assert.match(services, /Toll is the engineering economics product/)
    assert.doesNotMatch(services, /I focus/)
    assert.doesNotMatch(services, /I ship/)
    assert.doesNotMatch(services, /what I would do/)
    assert.doesNotMatch(services, /without a full-time hire/)
  })

  it('hides the skip link until keyboard focus', () => {
    const css = readFileSync(join(root, 'src/styles/site.css'), 'utf8')
    assert.match(css, /\.skip-link:focus-visible/)
    assert.match(css, /clip-path: inset\(50%\)/)
  })
})
